/**
 * Copyright (c) 2025 Microblink Ltd. All rights reserved.
 */

export const backDualWideCameraLocalizations = [
  "Cameră dublă cu obiectiv superangular spate",
  "מצלמה כפולה רחבה אחורית",
  "Артқы қос кең бұрышты камера",
  "Câmara grande angular dupla traseira",
  "Πίσω διπλή ευρεία κάμερα",
  "後置雙廣角鏡頭相機",
  "Задна двойна широкоъгълна камера",
  "Càmera dual posterior amb gran angular",
  "Zadná duálna širokouhlá kamera",
  "كاميرا خلفية مزدوجة عريضة",
  "Задняя двойная широкоугольная камера",
  "Задня здвоєна ширококутна камера",
  "Cámara amplia posterior doble",
  "Dwikamera Lebar Belakang",
  "Tylny dwuobiektywowy aparat szerokokątny",
  "Dubbel vidvinkelkamera på baksidan",
  "Back Dual Wide Camera",
  "Hátsó, kettős, széles látószögű kamera",
  "후면 듀얼 와이드 카메라",
  "Double caméra grand angle arrière",
  "Fotocamera doppia con grandangolo (posteriore)",
  "Double appareil photo grand angle arrière",
  "Zadní duální širokoúhlý fotoaparát",
  "Çift Geniş Kamera Arka Yüzü",
  "Laajakulmainen kaksoistakakamera",
  "Rückseitige Dual-Weitwinkelkamera",
  "बैक ड्युअल वाइड कैमरा",
  "后置双广角镜头",
  "Câmera Dupla Grande-Angular Traseira",
  "後置雙廣角相機",
  "กล้องคู่ด้านหลังมุมกว้าง",
  "Kamera Lebar Belakang Ganda",
  "Dobbelt vidvinkelkamera bak",
  "Camera kép rộng mặt sau",
  "Cámara trasera dual con gran angular",
  "背面デュアル広角カメラ",
  "Stražnja dvostruka široka kamera",
];
